# RuboCop config file
# Configure cops
# https://github.com/bbatsov/rubocop
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# https://github.com/bbatsov/ruby-style-guide
#

AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Puppetfile'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
    - 'modules/**/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

#################### Layout ###############################

# The shebang stuff at the top triggers this
Layout/LeadingCommentSpace:
  Exclude:
    - Puppetfile

#################### Style ###############################

# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# Support ruby 1.8.7
Style/HashSyntax:
  EnforcedStyle: hash_rockets

#################### Metrics ###############################

Metrics/LineLength:
  # Ruduce this... Max: 80
  Max: 112

Metrics/BlockLength:
  Enabled: false

##################### Bundler ##############################

Bundler/DuplicatedGem:
  Enabled: false
